// <auto-generated />
using Bot.StrategyCatalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace bot.Migrations
{
    [DbContext(typeof(StrategyConfigContext))]
    partial class StrategyConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Bot.StrategyCatalog.StrategyConfig", b =>
                {
                    b.Property<int>("StrategyConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyId")
                        .HasColumnType("TEXT");

                    b.HasKey("StrategyConfigId");

                    b.ToTable("configs");
                });
#pragma warning restore 612, 618
        }
    }
}
